### PR TITLE
Today page with check-in buttons

### LINKED ISSUE #281: ⚡ Making the TodayPage work
TodayPage mobile UI is ready but nothing is working yet.

@nsunami 🙏🏽

### PR DESCRIPTION
**Pull request by nsunami**
This PR makes it possible to check in and out from the today page.

I did not implement the sort and filter function. Also, we have checkboxes, but we can't check in multiple people at the same time. 

Resolves #281

### CODE REVIEW

**Review by jazellemaira — CHANGES_REQUESTED** [review]
The time on the ShiftSummary tab was not updated after changing the check-in time.

Also, can we check the format for the hours worked? 
In this video, the hours worked should be 1 hour and 4 minutes. The computation was correct but it might seem more natural to have 1:04 instead of 1:4.
 
https://github.com/user-attachments/assets/6f479bd5-89a3-45de-811c-4e9829037dfb

**Comment by nsunami** [comment]
I think I was able to fix it 👍  could you check again? @jazellemaira

**Comment by jazellemaira** [comment]
Found another edge case...right now, users can input a check-out time that is earlier than the check-in time making the total hours worked into a negative value.

Screenshot 2024-10-29 at 14 17 24

**Review by jazellemaira — CHANGES_REQUESTED** [review]
Added a comment. Please revise. 🙏🏽

**Comment by nsunami** [comment]
@jazellemaira Could you check this again?

**Review by jazellemaira — APPROVED** [review]
LGTM! 👍🏽 ✨

**Pull request merged**
